### ISSUE TITLE
[Feature Request] Share FFT memory between equalizers (overlay FFTs to find frequency conflicts)

### ISSUE THREAD

**Issue by PROPHESSOR** [lsp-plugins/lsp-plugins-para-equalizer#5]
Like it works in Fabfilter Pro Q 3:

![Image](https://github.com/lsp-plugins/lsp-plugins-para-equalizer/assets/19251320/fc23b69b-bc9c-457b-a42f-211b776040a1)

- [ ] Add a dropdown where you can see all other equalizer instances
- [ ] Overlay an FFT of them
- [ ] Highlight the most conflicting part (optional)
- [ ] Allow to use sidechain input for it

**Comment by sadko4u** [comment]
I think this feature can be closed now after 1.2.18 release of plugins.
